[package]
name = "ml-bot"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libtetris = { path = "../libtetris" }
serde = "1.0"
serde_json = "1.0"
nalgebra = "*"
rand = "0.8.4"
rand_distr = "0.4.2"
