[package]
name = "deep-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
anyhow = "1.0"
rayon = "1.5"
smallvec = { version = "1.10.0", features = ["const_generics"] }

[profile.release]
debug = true

[dev-dependencies]
sdl-gui = { path = "../sdl-gui" }
